### PR TITLE
Require/ban the width descriptor based on presence of sizes. Fixes #114

### LINKED ISSUE #114: Authoring conformance when sizes is present
It doesn't make sense to do `` however that is allowed. I think when the sizes attribute is present, all image sources in the source set must have the width descriptor specified.

### PR DESCRIPTION
**Pull request by zcorpan**

### CODE REVIEW

**Comment by tabatkins** [comment]
Use `<var>` rather than `<i title>` for the algo variables.

Otherwise, looks good.

**Comment by zcorpan** [comment]
I was trying to match the HTML spec which uses `<i>`. They're not really variables.

**Comment by tabatkins** [comment]
Well, they're either variables, or they're links to defined terms, or they don't really deserve to be marked up, right?

**Comment by zcorpan** [comment]
...no? They are not variables. They are terms, but giving them a definition and linking to it wouldn't make the spec any easier to read or understand. If you feel strongly about it I guess I can `<dfn>` them but I hope this whole spec is going to be merged into HTML soon anyway so this will become moot point.

**Comment by zcorpan** [comment]
Merging based on "Otherwise, looks good." above. Let's discuss the markup in a new PR if you still care about it (`i` is used in the spec before this change already).

**Pull request merged**
