### PR TITLE
Avoid adding src to the source set when using 'w'. Fixes #119

### LINKED ISSUE #119: Ignore src="" when sizes="" is present?
Since the `` attribute cannot have a width descriptor, it might not make much sense to add it to the source set when the sizes attribute is present.

### PR DESCRIPTION
**Pull request by zcorpan**
(Also fix nearby editorial bugs)

### CODE REVIEW

**Comment by yoavweiss** [comment]
Just to conclude our discussion from IRC: Basically we have 3 options when it comes to a source set that has a mix of image candidates with width and density descriptors:
1) Current algorithm, which normalizes the width descriptors into density descriptors, and picks the best candidate from that set.
2) Your proposed algorithm, which does the same thing, but excludes candidates that came from an `src` attribute, if there are width descriptors involved.
3) If there are width descriptors, we ignore all density descriptors, and only then normalize.

I'm not sure which option is the best one, and you're probably right that (2) will be less confusing for authors than current (1), but I think this merits a discussion. 

@Wilto & @tabatkins - what do you think?

**Comment by Wilto** [comment]
I talked this over with a couple of the devs at FG and the expectation all around was the way that the current algorithm works, so I’m wondering if we should remove the restriction there.

**Comment by tabatkins** [comment]
I don't think we should do (2) ever.  The `src` value is meant to be interpreted _exactly_ as a candidate with a `1x` descriptor; I don't see any good argument for differentiating it.

Discussion with @yoavweiss pointed out that the w descriptor _always_ makes sense, even if `sizes` is omitted.  So, I'm torn on the choice between (1) and (3).  :/

**Comment by Wilto** [comment]
I dunno about three. Any situation where something I’ve specified is silently thrown away is instantly confusing for me.

**Comment by tabatkins** [comment]
I am now second-guessing myself on all of this.  The fact that `src` is _only_ used to help downlevel browsers, and is useless in up-level ones, means that it might be okay to treat it specially, like (2) does.

I mean, I see the argument against silently dropping x candidates if there are any w candidates.  That makes sense - even if we require authors not to mix them because it's confusing, ignoring candidates that are otherwise syntactically valid is also confusing.

But I don't really see a reason to ever choose the `src` candidate if the `srcset` is using w candidates.  The fact that you're trying to accommodate older browsers shouldn't accidentally and confusingly mess up your well-crafted `srcset` list.

On the other other hand, special-casing like this is _also_ confusing. We're damned if we do, damned if we don't, and now I'm all kinds of confused.  I'll have to think on this.

**Comment by zcorpan** [comment]
So let's bring up some examples to try to make this more clear (hopefully).

When using `x` descriptors, we definitely want to use `src` also if it's not already in `srcset` so you can do this:

```
<img src="small.jpg" srcset="big.jpg 2x">
```

When using `w` descriptors, you will most likely want to use one of the images already in `srcset` as the value in `src` since that would make sense to use as fallback, and you want all candidates to have the `w` descriptor:

```
<img src="big.jpg" srcset="small.jpg 500w, big.jpg 1000w, bigass.jpg 2000w">
```

The question for this PR is, what should happen if you use something else in `src`?

```
<img src="somethingelse.jpg" srcset="small.jpg 500w, big.jpg 1000w, bigass.jpg 2000w">
```

If it's added as a `1x` candidate, it might get picked but it's hard to explain when and why.

I could be convinced to do (1) and put in an authoring requirement to have `src` be redundant with an item already specified in `srcset` when there are `w` descriptors.

I'm not sure (3) is a good option. Why is `w` used but not `x`, and not the other way around? What if you typoed one candidate to use the wrong descriptor?

**Comment by tabatkins** [comment]
Screw it, let's go with #2. I'm happy to merge this PR if anyone else agrees with me.

**Comment by yoavweiss** [comment]
:+1:

**Comment by Wilto** [comment]
+1

**Pull request merged**
