### PR TITLE
Enable multiple sources without `media` when `type` is involved

### PR DESCRIPTION
**Pull request by yoavweiss**
@zcorpan - can you please review?

### CODE REVIEW

**Comment by tabatkins** [comment]
Whitespace is wrong. (Use tabs, and configure your editor to either match the document's ws style, or show ws visibly so it's more obvious when you mess up.)

Is there a reason to disallow setting type to jpeg/etc?  I understand that it doesn't really function as a filter at that point, but it also makes it clearer if there are multiple `<source>`s that use `type=''`.  On the other hand, making validators complain about cargo-culting is possibly valuable, so I can go either way on this.

**Comment by zcorpan** [comment]
I don't think it works to say a type supported by all browsers, since specs are usually codec-agnostic and what is supported by "all browsers" changes over time and depends on your definition of "all" (and "browsers"). So I think we should allow any value or possibly ban a hardcoded set.

**Comment by yoavweiss** [comment]
> Whitespace is wrong. (Use tabs, and configure your editor to either match the document's ws style, or show ws visibly so it's more obvious when you mess up.)

Per directory vimrc it is...

> Is there a reason to disallow setting type to jpeg/etc?
> I didn't intend to disallow jpeg, only to make sure that multiple sources have meaningful differentiators between them (so either meaningful media or meaningful type).
> I thought it would make sense to match the logic of "only media values that make a difference" with the type definition.
> 
> I think we should allow any value or possibly ban a hardcoded set

I don't think specifying the types is worth the hassle. I'll remove it, allowing any type.

**Comment by yoavweiss** [comment]
Updated. Kept a "valid MIME type" restriction. Let me know if it makes sense or not (and if it should be marked up to link to a definition)

**Comment by zcorpan** [comment]
type is already required to have a valid MIME type as its value in HTML. So you can remove that here.

**Pull request merged**
