### PR TITLE
Rebase w3c-tr branch

### PR DESCRIPTION
**Pull request by zcorpan**

### CODE REVIEW

**Comment by yoavweiss** [comment]
LGTM. Needs rebasing tho

**Comment by marcoscaceres** [comment]
I'd like for us to **NOT** publish a snapshot. If the W3C wants to use this spec, it should come straight out of the HTML spec via the WHATWG fork. I think @tabatkins agrees with me here.

**Comment by marcoscaceres** [comment]
To be clear, it's not a requirement as per the W3C process that we publish a heartbeat snapshot. That's just some bullshit the HTMLWG made up.

**Comment by marcoscaceres** [comment]
I propose we focus on making sure this ends up in the WHATWG spec ASAP instead.

**Comment by Wilto** [comment]
I’d agree with you if this W3C spec weren’t tripping people up. I still see people tweeting the link like “hooray, [picture’s] srcset is coming,” and even Microsoft has it linked up under their “under consideration” for `srcset`. This thing is causing confusion, but not benefitting anybody as-is.

**Comment by tabatkins** [comment]
If _that's_ the only concern, there's a much easier fix - put up a simple document saying "This version of the spec is obsolete and no longer being worked on, look over here instead." and have it redirect automatically as well.

**Comment by marcoscaceres** [comment]
I agree with @tabatkins. That solves the problem.

**Pull request closed without merging**
