### PR TITLE
Clarifying the “relationship to `srcset`” section.

### PR DESCRIPTION
**Pull request by Wilto**
No major changes here; just being explicit about the fact that this `srcset` replaces the original proposal, and some general copy edits.

### CODE REVIEW

**Comment by tabatkins** [comment]
Sounds good. Wanna re-up the patch so it's mergeable?  I suspect it's the .html version that's causing problems.

**Comment by Wilto** [comment]
Oh, weak. I’ll just cherry-pick it over to gh-pages.

**Comment by Wilto** [comment]
Ref. 194f19d400b2d6e8bb98dace49a595d8c067097f

**Comment by zcorpan** [comment]
@Wilto please update your bikeshed

**Comment by Wilto** [comment]
Will do.

**Pull request closed without merging**
